using System;
using System.ComponentModel.DataAnnotations;

namespace AMMS.Models
{
    public class Fault
    {
        /* DA PAM 738-751
         * Page 49
         * DA Form 2408-13-1, PART I
         * Aircraft Inspection and Maintenance Record: FAULT INFORMATION
         */

        [Key]
        public string Id { get; set; }

        /* PART I-FAULT INFORMATION: Any person who
         * discovers a fault or condition affecting the operation/flight
         * of the aircraft, training device/simulator, or mission
         * related equipment aboard the aircraft will record it in a
         * FAULT INFORMATION block.
         * STATUS: Enter the proper status symbol in this block.
         * Once a status symbol is entered in the STATUS Block,
         * it will not be erased or changed efen if entered in error
         * (para 1-8). The person who corrects a red "dash" or red
         * diagonal "/" fault will enter their last name initial over the
         * status symbol. A red "X" or circled red "X" status symbol
         * will be initialed over by a qualified designated representative
         * appointed by the unit or activity commander. When
         * clearing a red "X" or circled red "X" a ballpoint pen with
         * blue or black ink, or technical inspector's stamp may be
         * used. The maintenance test pilot will initial the symbol
         * after they complete the test flight and the aircraft is
         * cleared for flight. When more than one person completes
         * the corrective action for a fault, other than a
         * phase, periodic, or progressive phase maintenance, the
         * senior mechanic, who performed part of the corrective
         * action will initial the status symbol for entries with a red
         * diagonal "/" or red dash "-" status. Initials placed in this
         * block will not be erased.
         * 
         * Note. Changing the status symbol, for armament, electronic,
         * and other mission-related equipment, to a less
         * serious status symbol is not needed for a one time
         * evacuation mission per paragraph 1-10.
         */
        [Required]
        [Display(Name = "STATUS")]
        [RegularExpression(@"^[-/X+]{1}$")]
        public string Status { get; set; }

        /* SYS. ULLS-A users only: Enter the system code that
         * shows which system the fault is related to. System
         * Codes can be found on the DA Form 2408 in front of the
         * logbook. Code "A" will be used for all aircraft faults.
         * Electronic faults that do not affect aircraft readiness and
         * are not reportable under AMSS will also use code "A."
         * Electronic equipment faults that affect readiness and are
         * reportable under AMSS will use code "E." All armament
         * faults will use code "W."
         */
        [Display(Name = "SYS")]
        [RegularExpression(@"^\D{1}$")]
        public string Sys { get; set; }

        /* DATE: Enter the date (dd mmm yy) a fault is discovered,
         * or a remark is made. When the fault is reentered
         * from the DA Form 2408-14-1 the original date of the
         * fault will be entered.
         */
        [Display(Name = "DATE")]
        public DateTime Date { get; set; }

        /* NO: Leave blank for units using the manual recordkeeping
         * system. Computer generated by ULLS-A.
         */
        [Display(Name = "NO.")]
        public int? No { get; set; }

        /* TIME: Enter the time (24-hour clock) the fault was discovered,
         * or an inspection/service was entered. When a
         * fault is reentered from the DA Form 2408-14-1 leave
         * this block blank.
         */
        [Display(Name = "TIME")]
        public DateTime? Time { get; set; }

        /* PID: The person making the entry will enter his or her
         * personnel identifier.
         */
        [Required]
        [Display(Name = "PID")]
        [RegularExpression(@"^\D{2}\d{4}$|^\D{2}\d{6}$")]
        public string PID { get; set; }

        /* FAULT/REMARKS:
         * a. The person who finds a fault or removes a
         * component/module or part will immediately make an entry on
         * the first open line in the FAULT/REMARKS section.
         * Enter the proper status symbol in the STATUS block,
         * and update the status symbol on the DA Form 2408-13,
         * SYSTEM STATUS block, when it applies.
         * 
         * b. For ULLS-A/LAS users, when related maintenance
         * actions are needed to correct a fault, enter the primary
         * fault in the first open FAULT INFORMATION block on
         * the DA Form 2408-13-1. The related maintenance actions
         * will be entered on a DA Form 2408-13-2 (Related
         * Maintenance Actions Record). For users under the
         * manual recordkeeping system, if only one related
         * maintenance action is needed to correct a fault, it may be
         * entered on the DA Form 2408-13-1. If fore than one
         * related maintenance action is required, the related
         * maintenance actions will be entered on a DA Form 2408-13-2.
         * 
         * c. After a flight, if no faults are noted, the pilot will enter
         * a remark such as "Flt 1 OK," then enter his or her PID,
         * the date, time, and aircraft hours in the corresponding
         * blocks. If the pilot has a remark to make regarding the
         * aircraft or installed mission-related equipment, he or she
         * will enter the remark in the FAULT/REMARKS section,
         * PID in the PID block, and the date in the DATE block. If
         * faults or deficiencies are noted during the flight, the pilot
         * will procede the fault or deficiency entry with "FLT
         * (corresponding flight number for the mission day)," or "Test
         * Flight" if the fault or deficiency is discovered during a
         * test flight, along with his or her PID in the PID block,
         * and all applicable portions of the FAULT INFORMATION
         * block. Use as many Fault Information blocks as
         * necessary to enter faults, deficiencies, and remarks;
         * with only one fault/remark per FAULT INFORMATION
         * block. If more space is needed, to enter a fault/remark,
         * than is provided in a FAULT INFORMATION block then
         * enter "Continued" on the last line of the FAULT/
         * REMARKS section, and continue the fault/remark in the
         * next open FAULT INFORMATION block. If the fault/
         * remark will not fit the space provided in the last FAULT
         * INFORMATION block on the backside of the form, then
         * enter "Continued," at the end of the last line of the
         * FAULT/REMARKS section, and continue the fault/
         * remark on the next page.
         * 
         * d. When a test flight or MOC is needed after maintenance,
         * enter a red dash in the STATUS block, and
         * when it applies update the DA Form 2408-13, SYSTEM
         * STATUS block. In the FAULT/REMARKS section enter
         * "Test Flight Required," "Test flight due," "MTF required,"
         * "MTF due," or "MOC Required" and give the reason(s)
         * why.
         * 
         * e. Entries are also needed for aircraft accidents, forced
         * or precautionary landings, airspeed limitations, or engine
         * torque exceeded. Include the cause and damage, if any.
         * 
         * f. If an aircraft becomes contaminated, refer to paragraph
         * 1-8 and appendix B.
         * 
         * ACHRS: Enter the actual aircraft hours at the time the
         * inspection or service was entered, or when the fault was
         * discovered. Leave blank, when a fault is reentered from
         * the DA Form 2408-14-1.
         */
        [Display(Name = "AC HRS")]
        public double? AcHrs { get; set; }

        /* WHEN DISC. ULLS-A/LAS users: Enter the appropriate
         * When Discovered Code, for faults and discrepancies,
         * from DA Form 2408 or table 1-4. Leave blank
         * when a remark is in the FAULT/REMARKS section.
         */
        [Display(Name = "WHEN DISC")]
        [RegularExpression(@"^\D{1}$")]
        public string WhenDisc { get; set; }

        /* HOW REC. ULLS-A/LAS users: Enter the appropriate
         * How Recognized Code, for faults and discrepancies,
         * from DA Form 2408 or table 1-5. Leave blank when a
         * remark is in the FAULT/REMARKS section.
         */
        [Display(Name = "HOW REC")]
        [RegularExpression(@"^\D{1}$")]
        public string HowRec { get; set; }

        /* MAL EFF. ULLS-A/LAS users: Enter the appropriate
         * Malfunction Effect code, for faults and discrepancies,
         * from DA Form 2408 or table 1-6. Leave blank when a
         * remark is in the FAULT/REMARKS section.
         */
        [Display(Name = "MAL EFF")]
        [RegularExpression(@"^\d{1}$")]
        public string MalEff { get; set; }

        /* DELAY: Enter the reason for the delay: For example,
         * enter the work order number of the work request to fix
         * the fault or condition, or enter the supply requisition
         * number for a repair part that is required to repair the
         * fault, or enter "2408-13-2" when a DA Form 2408-13-2
         * is needed to list related maintenance actions for clearing
         * the fault or deficiencies. When a fault is reentered from
         * the DA Form 2408-14-1 leave blank.
         */
        [Display(Name = "DELAY")]
        public string Delay { get; set; }

        /* WUC. ULLS-A/LAS users: Enter the work unit code
         * (WUC) that best describes which component or module
         * the fault or inspection entry pertains to. If a WUC, that
         * applies to the component, module, or area, has not
         * been established enter the functional group code, from
         * DA Form 2408 or table 1-10, which best fits the fault or
         * inspection. Leave blank when a remark is in the FAULT/
         * REMARKS section.
         */
        [Display(Name = "WUC")]
        public string Wuc { get; set; }

        /* CORRECTING INFORMATION
         */
        public Correction correction { get; set; }

        /* RELATED MAINTENANCE
         */
        public DA2408_13_2 RelatedMaintenance { get; set; }

        private string DA2408_13_1Id { get; set; }
        private DA2408_13_1 MaintenanceRecord { get; set; }
    }
}
